##############################################
# yaml configuration file for PTA simulation #
##############################################
#
#NOTE: This is the template file in the git
#please copy and edit your copy for running purposes.
#
#NOTE: PyYAML is picky about parsing floats, and will happily revert to
#strings (!) for numbers in scientific notation.  Make sure you have
#    - a decimal point AND
#    - a sign attached to the exponent (e.g. 2.0e+4)
#
##############################################

### pulsar options ###
# specify random, from_file, from_array or from_csv
# from_file expects a PTA file with locations in Ra Dec etc, 
# from_csv expects a csv file with columns theta, phi, rms
pulsar_method: random

# if random, need to specify options below
# if from_csv, only need to specify num_pulsars and path to csv file below
pulsar_opts:
    num_pulsars: 5
    mean_rms: 1.0e-7
    sig_rms: 5.0e-8
    uniform: False
    weight_map_dir: null # use on cluster, path to dir with mps_weight_map.dat
    seed: null

# if from_file or from_csv, specify path to pulsar/csv file
pulsar_file: ./PTA_files/IPTA_pulsars.txt

# if from_array, need to specify pulsar locations and rms below
# each location is [theta, phi] with 0 < theta < pi and 0 < phi < 2pi
pulsar_array:
    - [0.8, 2.9] # these are some random oordinates
    - [1.9, 6.2]
    - [2.4, 4.0]
pulsar_rms:
    - 2.2e-7
    - 1.3e-7
    - 0.9e-7

### times opttions ###
# if True, use sim.evenly_sampled_times, and specify times_es_opts
# if False, use sim.randomized_times, and specify times_rd_opts
times_evenly_sampled: False

# some useful numbers
# 1 year = 31557600.0
# 5 years = 157788000.0
# 20 years =  631152000.0

times_es_opts:
    cadence: 1.0e+6
    T: 631152000.0
    t_start: 0.0

times_rd_opts:
    mean_cadence: 1.0e+6
    std_cadence: 1.0e+5
    min_cadence: 1.0e+5
    max_t_start: 0.0
    t_end: 631152000.0 
    gaps: True
    exp_gap_spacing: 157788000.0
    exp_gap_length: 1.0e+7
    seed: null
    

### signal and noise injection ###

# currently only have sinusoid_TD (a GW binary w/o inspiral) implemented
model_name: sinusoid_TD
true_source: [0.5, 0.5]
true_args: [0.5, 1.0e-14, 0.5, 0.5, 2.0e-8] # need to match args of chosen model

# if True, add white noise according to each pulsar's rms
white_noise: False
noise_seed: 1000
noise_scale: null # scale injected white noise by this factor (no effect if null or 1)

### plotting options ###

# plots are put in the output file specified in run_config
plot_pulsar_map: True
plot_residuals_TD: True
plot_residuals_FD: True

